### ISSUE TITLE
Render components from a layout object

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/analysis-ui-components#102]
We are currently trying to create a state that will allow to save a dynamic react components.

We did this proposal for a simple layout

https://hackmd.io/@lpatiny/HJ5sU2kb9

The goal of this issue is from the 'layout state' (see hackmd link) to recreate something like:

![image](https://user-images.githubusercontent.com/1484241/156796780-6af41e60-dfe7-42d2-b3ab-eeca3a3b5146.png)

this is a first proposal but we will invest a lot of ressource on those features.

**Comment by lpatiny** [comment]
@targos Where should this code be placed in order to test it ?

New section in storybook called dynamic layout ?

https://cheminfo.github.io/analysis-ui-components/?path=/story/layout-full-app--full-example

**Comment by targos** [comment]
A new section in the storybook sgtm for now

**Comment by lpatiny** [comment]
Closed by e3b93f0c2b22bbb3d8a27b057f2b2f4c2b662977
