### ISSUE TITLE
'About icon' not aligned

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/analysis-ui-components#47]
The top left icon is not aligned with the other icons in the left toolbar. Please could you fix this ?

It is also the case in https://dev.nmrium.org (as compared with www.nmrium.org).

![image](https://user-images.githubusercontent.com/1484241/133983030-d5a018ef-dbf0-4412-8f28-eed728d54bb9.png)

**Comment by targos** [comment]
duplicate of https://github.com/cheminfo/analysis-ui-components/issues/46
