### ISSUE TITLE
Card flip

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/analysis-ui-components#76]
For preferences we have in NMRium the following library: https://www.npmjs.com/package/react-card-flip

However if I understand well it is buggy and when the card is flipped, in google chrome, we need to hide manually the table.

There may be a fixe in the library: https://github.com/AaronCCWong/react-card-flip/pull/61 but it was never merged.

I think we could add in this library HorizontalFlip that would do the same as this external library.

**Comment by lpatiny** [comment]
Currently this is the behaviour for the preferences.

![2021-11-12 14 34 55](https://user-images.githubusercontent.com/1484241/141475580-2e0d61bc-8c7b-413d-a0a8-2366e8433789.gif)

@wadjih-bencheikh18 do you have another proposal ? Maybe without the flip.

**Comment by wadjih-bencheikh18** [comment]
the size of this window decrease in the direction of the (x) until it disappear will be much better
