### ISSUE TITLE
Create a component 'PlotXY'

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/analysis-ui-components#81]
In the 'Full application' we would like to move forward to reuse all the components and create a 'real' application.

This real application is available by using `npm run vite` and we will deploy it soon on gh-pages.

This requires to add a new component `PlotXY` that will allow to display MeasurementXYVariables
https://github.com/cheminfo/cheminfo-types/blob/main/src/measurements/common/MeasurementXYVariables.d.ts

This means we have some data in the form of

```json
{
  x: {label: 'abc', data: [1,2,3]},
  y: {label: 'def', data: [2,3,4]},
}
```

This `PlotXY` component will optionally display X and Y axis the data using:

https://github.com/zakodium/react-d3-utils do display the scale.

Here is some data that can be used in the complete application to test:

[variables.json.zip](https://github.com/cheminfo/analysis-ui-components/files/7528354/variables.json.zip)

The final result should look like:

![image](https://user-images.githubusercontent.com/1484241/141488589-b402718b-2eaa-4688-888e-777f75584395.png)

Please be aware that we will need in the future to have:
- crosshair
- zoom (vertical and horizontal)
- superimposition of many spectra

Please note that we don't use d3.js to manipulate the dom. The dom is managed by React. However there are many very practical utilities in d3.

Some useful code may be copied from https://github.com/zakodium/react-plot

**Comment by wadjih-bencheikh18** [comment]
@lpatiny Should lines between data points be straight or curved?

**Comment by wadjih-bencheikh18** [comment]
do i have to copy the code from https://github.com/zakodium/react-plot or it's enough to use the package?
is reverse axis feature included? (in the exmple x is reversed)

**Comment by lpatiny** [comment]
@targos Those 2 questions from Wadjih I can not answer:

![image](https://user-images.githubusercontent.com/1484241/146655593-44c59180-2a00-40d8-972b-7d9617e034a6.png)

**Comment by wadjih-bencheikh18** [comment]
> @targos Those 2 questions from Wadjih I can not answer:
> 
> ![image](https://user-images.githubusercontent.com/1484241/146655593-44c59180-2a00-40d8-972b-7d9617e034a6.png)

thank you,
about the component u want it to have one props (data) and do everything
or you want a more details (the user have to add axes and lines (with diffrent props )

**Comment by targos** [comment]
Should we close this (and the PR) now that we are focusing on `react-plot` ?
